cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - .stack-work
    - .stack-root

stages:
  - build
  - release
  - deploy

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack-root"
  LANG: "C.UTF-8"

  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  DOCKER_DRIVER: overlay2

  KUBECONFIG: /etc/deploy/config

build:
  stage: build
  image: fpco/stack-build:lts-14.10
  script:
    - git submodule update --init --recursive || git clean -fdx && git submodule update --init --recursive || rm -rf sites && git submodule update --init --recursive
    - rm -rf docker/artifacts
    - mkdir -p docker/artifacts/app/yesodweb.com docker/artifacts/app/webapps docker/artifacts/bin
    - stack install --local-bin-path docker/artifacts/bin
    - cp -r sites/yesodweb.com/config sites/yesodweb.com/static docker/artifacts/app/yesodweb.com
    - cp -r webapps/config docker/artifacts/app/webapps
  artifacts:
    paths:
     - docker/artifacts

release:
  stage: release
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE} docker
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}

# FIXME!
deploy:
  stage: deploy
  only:
    - master
  variables:
    DEPLOYMENT_NAME: "snoyman-webapps"
  script:
    - kubectl set image "deployment/$DEPLOYMENT_NAME" webapps=${CONTAINER_IMAGE}
    - kubectl rollout status "deployment/$DEPLOYMENT_NAME"
