resolver: lts-6.30

packages:
- webapps
- sites/dollarversusshekel
- sites/haskellers
- sites/luach
- sites/snoyman.com
- sites/whosawthatcoming
- sites/yesodweb.com
- location: vendor/gitrev
  extra-dep: true
- location:
    git: https://github.com/snoyberg/warp-letsencrypt
    commit: 138426715f9666fd2d3c5a16c37004f449efac85
  extra-dep: true

image:
  container:
    name: snoyberg/snoyman-webapps
    base: snoyman-webapps-base
    add:
      sites/yesodweb.com/config: /app/yesodweb.com/config
      sites/yesodweb.com/static: /app/yesodweb.com/static

      sites/haskellers/config: /app/haskellers/config
      sites/haskellers/static: /app/haskellers/static

      sites/whosawthatcoming/config: /app/whosawthatcoming/config
      sites/whosawthatcoming/static: /app/whosawthatcoming/static

      sites/luach/static: /app/luach/static

      sites/whosawthatcoming/config: /app/whosawthatcoming/config
      sites/whosawthatcoming/static: /app/whosawthatcoming/static

      webapps/config: /app/webapps/config
