resolver: lts-14.10

packages:
- webapps
- sites/snoyman.com
- sites/yesodweb.com

image:
  container:
    name: snoyberg/snoyman-webapps
    base: snoyman-webapps-base
    add:
      sites/yesodweb.com/config: /app/yesodweb.com/config
      sites/yesodweb.com/static: /app/yesodweb.com/static

      webapps/config: /app/webapps/config
