resolver: lts-10.5

packages:
- webapps
- sites/snoyman.com
- sites/yesodweb.com
- location: vendor/gitrev
  extra-dep: true

image:
  container:
    name: snoyberg/snoyman-webapps
    base: snoyman-webapps-base
    add:
      sites/yesodweb.com/config: /app/yesodweb.com/config
      sites/yesodweb.com/static: /app/yesodweb.com/static

      webapps/config: /app/webapps/config
