resolver: lts-12.0

packages:
- webapps
- sites/snoyman.com
- sites/yesodweb.com

extra-deps:
- githash-0.1.0.1@sha256:fd8110389b1e4febf2bca0acfca6505130606233058a3cdab96bd66d7b359b84,1552

image:
  container:
    name: snoyberg/snoyman-webapps
    base: snoyman-webapps-base
    add:
      sites/yesodweb.com/config: /app/yesodweb.com/config
      sites/yesodweb.com/static: /app/yesodweb.com/static

      webapps/config: /app/webapps/config
