index-vhost: webapps.snoyman.com
title: Michael Snoyman's webapps

apps:
- vhost: www.yesodweb.com
  dir: /app/yesodweb.com
  exe: yesodweb
  args:
  - production
  desc: Yesod Web Framework homepage
- vhost: www.snoyman.com
  dir: /app
  exe: snoymancom
  args:
  - production
  desc: Michael Snoyman's personal homepage

redirects:
- src: yesodweb.com
  dst: www.yesodweb.com
- src: yesodweb.org
  dst: www.yesodweb.com
- src: www.yesodweb.org
  dst: www.yesodweb.com
- src: docs.yesodweb.com
  dst: www.yesodweb.com
- src: old.yesodweb.com
  dst: www.yesodweb.com
- src: beta.yesodweb.com
  dst: www.yesodweb.com
- src: snoyman.com
  dst: www.snoyman.com
- src: michael.snoyman.com
  dst: www.snoyman.com
- src: snoyberg.com
  dst: www.snoyman.com
- src: www.snoyberg.com
  dst: www.snoyman.com
