apiVersion: v1
kind: Service
metadata:
  name: snoyman-webapps
  labels:
    app: snoyman-webapps
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: webapps
  selector:
    app: snoyman-webapps
